### ISSUE TITLE
Cors Error

### ISSUE THREAD

**Issue by DarkShadow8700** [emulatorjs/emulatorjs#222]
When I load a game I get an error saying cors error and I see the same error for other systems as well 
![Screenshot 2022-05-06 9 22 39 PM](https://user-images.githubusercontent.com/96354083/167234191-fb952f66-aea1-4023-904a-9e6378e7c655.png)

**Comment by ethanaobrien** [comment]
are you using the github.io link to play?

**Comment by DarkShadow8700** [comment]
Yes

**Comment by ethanaobrien** [comment]
Clear your cache

**Comment by ethanaobrien** [comment]
@DarkShadow8700 Clear your browser cache (go into settings) and then try it again. I just pushed some fixes

**Comment by DarkShadow8700** [comment]
Alright I will be sure to do that

**Comment by DarkShadow8700** [comment]
I have 1 more question though I tried the githack site and I'm still seeing the Cors error.

**Comment by ethanaobrien** [comment]
I'm not getting this error at all. Can you try on a different device?

**Comment by DarkShadow8700** [comment]
I tried on a different computer and it seemed to work it must be something wrong with my computer. But thanks for the help though

**Comment by ethanaobrien** [comment]
No problem! Most likely your computer is still caching something, sorry. You can possibly fix this by opening inspect and clicking on the network tab and then clicking the do not use cache option
