### ISSUE TITLE
Raw Githack error 

### ISSUE THREAD

**Issue by Bobgills** [emulatorjs/emulatorjs#259]
I've been experiencing an issue I don't know if its the emulator's fault or not but  when playing the githack version of the emulator the issue is whenever I try to load a game I get an issue that githack is either down or it's offline
![Screenshot 2022-05-26 12 03 36 PM](https://user-images.githubusercontent.com/105334946/170538985-665e2853-001b-471d-9c7d-65a99664ef61.png)

**Comment by ethanaobrien** [comment]
Fixed. Update the button

**Comment by Bobgills** [comment]
Thanks

**Comment by Bobgills** [comment]
I tried on 2 different devices and the problem is still showing up @ethanaobrien

**Comment by ethanaobrien** [comment]
Clear your cache, update the button
