### ISSUE TITLE
EmulatorJS freeze on "loading" message when try set the parameter "EJS_startOnLoaded = true;"

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#289]
Hi,

When i try to enable this parameter "EJS_startOnLoaded = true;" - the script freeze with a "loading" message without loading the rom first.
I've attached a screenshot of the embed script with the console, and also the console log file.

I'll appreciate your help.
Thank you.

Here is the files:
![freeze in loading](https://user-images.githubusercontent.com/10597517/178469978-96d507a1-d322-4ce0-9bc6-2c428d1b3d80.jpg)
[console.log](https://github.com/ethanaobrien/emulatorjs/files/9091987/console.log)

**Comment by allancoding** [comment]
Are you using beta?
What core are you using?
What are the other parameters you are using?
This will help troubleshoot the problem.
Thank you

**Comment by shaylevary** [comment]
<div id=\"playframe\" style=\"width:"800px;height:"600"px;max-width:100%\">
<div id=\"game\"></div>
</div>
Hi,
Thank you for your replay, this problem appears on every core i try to set (sega,snes,psx) - when "EJS_startOnLoaded" is set to "true".

Here is my parameters:

<script type=\"text/javascript\">
		EJS_player = '#game';
		EJS_startOnLoaded = true;
		EJS_gameUrl = '';					
		EJS_pathtodata = '';		
		EJS_core = '';
		EJS_mouse = false;
		EJS_multitap = false;
		EJS_BETA = true;
		EJS_DEBUG_XX = true;
</script>

**Comment by allancoding** [comment]
This might be a problem related to using beta cores. First beta cores are only snes, nes, gb, and nds.
Try turing beta and debugging off that should fix it.

**Comment by ethanaobrien** [comment]
This is not a problem with beta

**Comment by shaylevary** [comment]
I disable both beta and debug, but it still freeze on loading message when enabling "EJS_startOnLoaded", so I guess it's some bug.

**Comment by ethanaobrien** [comment]
Correct, This is a bug

**Comment by imneckro** [comment]
Anyone has any leads on how to fix this?

**Comment by ethanaobrien** [comment]
I have this fixed, I’m working on a few things before I push my changes. It should be done on Monday. 

The problem is that the emulator will not start if the user hasn’t engaged with the document. That’s why it’s not starting. I plan to fix by just not hiding the play now button

as long as the user interacts with the document it should be fine. This will be required because the emulator cannot start properly without it

**Comment by imneckro** [comment]
@ethanaobrien Thanks Ethan again for your hard work. Too bad though. All this time I got used to autostart. I'll miss it :*(

**Comment by ethanaobrien** [comment]
Yeah, I really like working on this project the users make it worth it.

autostart will still work as long as the user has clicked/interacted with the page, like if your site is a single page app. This is mainly a browser thing, so that’s what I gotta do to work around it

**Comment by ethanaobrien** [comment]
Fixed!

**Comment by shaylevary** [comment]
Hi,

Sorry, but it still doesn't work. 
Currently it just ignore this parameter (EJS_startOnLoaded=true) and required me to click the "Start Game" button.

**Comment by ethanaobrien** [comment]
Look in the console, it includes why

**Comment by ethanaobrien** [comment]
@shaylevary @imneckro Very sorry, I was completely wrong. Download and try the new files, they should work. The start on load function should start as intended (the bug was a race condition)

**Comment by shaylevary** [comment]
Hi,

Thank you for the update, i've checked it now, and it seems to loads the game directly (without the need to press the start button), but if I refresh the same page, after it loads the core file and the game files I get a black screen (on the pc web browser the browser freezes, on my mobile phone, if I click on the screen several times the game suddenly loaded).

It seems that there is still a problem with the user interaction with browser after refreshing the game page.

**Comment by ethanaobrien** [comment]
I cannot detect whether or not the user has interacted with the page. The ability to fix that is not possible, it is a browser security policy. Start on load should only be used in cases like the demo where you have to interact with the page and it’s loaded later

**Comment by shaylevary** [comment]
Ok, Thank you for trying anyway.

**Comment by p1u3m** [comment]
Is this fix now ???
