### ISSUE TITLE
Downgrade shaders for old cores

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#341]
Hi,

I've noticed today that the Shader option doesn't work on PSX core. I've tried to select different shaders, but there was no change.
I will appreciate if you can please check this issue.
![shader_psx](https://user-images.githubusercontent.com/10597517/186401893-833cb728-4c60-4d24-bc30-70b7d327b545.jpg)

**Comment by ethanaobrien** [comment]
Fixed

**Comment by shaylevary** [comment]
Hi,
I've download and test the latest build, but it still doesn't seems to work under psx core, no matter which shader i choose.

**Comment by ethanaobrien** [comment]
Then it might be that specific core. I cant do anything to fix that
