### ISSUE TITLE
All cores not functioning on iOS

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#342]
I've found that trying to play anything on the last few updates doesn't work at all on iOS. I can't test this further right now but I'll try to get my hands on something to test further

**Comment by ethanaobrien** [comment]
Hey @Ramaerel I was wondering if you wouldn't mind being a beta tester. I haven't released the new code yet to anyone online and I have 3 other people who are beta testing so far. Would you like to be a beta tester? I'm about 1 month from getting this new version into a workable state.

**Comment by Ramaerel** [comment]
That would be amazing, I can absolutely do that. Thank you for considering me 🙂

**Comment by ethanaobrien** [comment]
Awesome, thank you. I'll reach out to you when it's ready to test

**Comment by ethanaobrien** [comment]
Hello @Ramaerel I was wondering if you had an email I could use to contact you. I had a few questions I wanted to ask and I wanted to share a list of the planned/already done features I plan to include in the next update. My email is ethan.a.obrien@gmail.com if you want to just email me that way. Thanks!

**Comment by Ramaerel** [comment]
Hey man, I'll.gladly help out where I can. My best contact email is cbean2000@outlook.com
I may not be able to get back to you straight away, depending on the time- But I will when I can

**Comment by ethanaobrien** [comment]
Awesome, thank you

**Comment by ethanaobrien** [comment]
Migrated to https://github.com/emulatorjs/emulatorjs/issues/1

**Comment by ethanaobrien** [comment]
Actually - I just transferred the repository

**Comment by ethanaobrien** [comment]
I havent tested on ios on the new version. If  anyone could thatd be helpful

**Comment by ethanaobrien** [comment]
This should be fixed

**Comment by ethanaobrien** [comment]
Wait - after testing it looks like safari just doesn't like the minified JavaScript file. I just need to not use the minified file on iOS (which is annoying)

**Comment by Vimm2** [comment]
It's not just Safari, I get this error in FireFox 105.0.1.  Chrome works though.

```
Uncaught TypeError: t is undefined
    d https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    l https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    oncomplete https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    get https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    l https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    promise callback*l https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    k https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    R https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    I https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    monitorRunDependencies https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    removeRunDependency https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5 line 1 > eval:1
    receiveInstance https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5 line 1 > eval:1
    receiveInstantiationResult https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5 line 1 > eval:1
    promise callback*instantiateArrayBuffer https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5 line 1 > eval:1
    instantiateAsync https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5 line 1 > eval:1
    createWasm https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5 line 1 > eval:1
    <anonymous> https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5 line 1 > eval:1
    L https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    j https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    n https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    L https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    promise callback*L https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    d https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    promise callback*d https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    z https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    oncomplete https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    get https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    z https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    promise callback*z https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    e https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    c https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    c https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    ie https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    create https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    nt https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    nt https://vimm.net/vault/emulatorjs/data/emulator.min.js?v=30.5:1
    <anonymous> https://vimm.net/vault/emulatorjs/data/loader.js:93
    async* https://vimm.net/vault/emulatorjs/data/loader.js:95
```

**Comment by ethanaobrien** [comment]
That's strange, I think I get a different error on safari though, I'll debug this when I can

**Comment by ethanaobrien** [comment]
@Vimm2 would you mind getting me a log of that with `EJS_DEBUG_XX` set to true?

**Comment by Vimm2** [comment]
Sorry for the confusion, I assumed it was the same issue.  Here's the log and url to reproduce it:
https://vimm.net/vault/?p=emulatorjs&id=834

```
Uncaught TypeError: _0x1844e3 is undefined
    _0x3512e9 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:1565
    _0x5048db https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:1681
    oncomplete https://vimm.net/vault/emulatorjs/data/emulator.js?v=30.5:510
    get https://vimm.net/vault/emulatorjs/data/emulator.js?v=30.5:509
    _0x5048db https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:1679
    promise callback*_0x5048db https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:1631
    _0x139f68 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:1748
    _0x452592 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:1808
    _0x10b71a https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:1960
    monitorRunDependencies https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:1971
    removeRunDependency https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5 line 2000 > eval:1
    receiveInstance https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5 line 2000 > eval:1
    receiveInstantiationResult https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5 line 2000 > eval:1
    promise callback*instantiateArrayBuffer https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5 line 2000 > eval:1
    instantiateAsync https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5 line 2000 > eval:1
    createWasm https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5 line 2000 > eval:1
    <anonymous> https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5 line 2000 > eval:1
    _0x54d695 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:2000
    _0x4f0fcc https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:2012
    _0xbae705 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:255
    _0x21d6a1 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:2016
    _0x4f0fcc https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:2025
    promise callback*_0x4f0fcc https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:2024
    _0x3641d6 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:2107
    promise callback*_0x3641d6 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:2100
    _0x26d6a1 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:2227
    oncomplete https://vimm.net/vault/emulatorjs/data/emulator.js?v=30.5:510
    get https://vimm.net/vault/emulatorjs/data/emulator.js?v=30.5:509
    _0x26d6a1 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:2218
    promise callback*_0x26d6a1 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:2120
    _0x5127f4 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:240
    _0x1ef215 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:208
    _0x1ef215 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:202
    _0x455c85 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:235
    create https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:2295
    _0x3dbc76 https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:6922
    _0x6954aa https://vimm.net/vault/emulatorjs/data/emu-main.js?v=30.5:6710
    <anonymous> https://vimm.net/vault/emulatorjs/data/loader.js:93
    async* https://vimm.net/vault/emulatorjs/data/loader.js:95
emu-main.js:1565:45
```

**Comment by ethanaobrien** [comment]
Thank you, I'll look at this. From the look of the error this is probably just a variable defined with let being used outside its scope

**Comment by hadoizz** [comment]
can you send me beta tester please hadoidxb@gmail.com

**Comment by ethanaobrien** [comment]
No, I've chosen a very small amount of people to beta test and from the sounds of it you don't quite have the required skills to set it up. At the moment this project and the beta version are both at the same state, meaning all the code in beta is currently in the main code.

**Comment by Wamy-Dev** [comment]
is this problem still being worked on? I cant seem to get it working on any browser. iOS 15.4.1, iPhone 12 Pro. Tried safari, chrome and brave. Just stays on "loading".

**Comment by ethanaobrien** [comment]
Sorry, I have been busy, yes I plan to fix this. I think I know what's wrong

**Comment by ethanaobrien** [comment]
This is theoretically fixed. Can someone check this?

**Comment by Wamy-Dev** [comment]
Checked. Still stays on loading. Still not working.

**Comment by ethanaobrien** [comment]
Hmm, this is a weird problem. I'll do more testing when I can. Thank you

**Comment by Wamy-Dev** [comment]
For anyone on iOS, if you want an easy way to test, I have set up eruda on my production website. [Please try it here](https://rezi.one/play?type=n64&link=https://archive.org/download/nointro.n64/Mario%20Kart%2064%20%28Europe%29%20%28Rev%201%29.7z&bios=null&title=Mario%20Kart%2064%20(Europe)%20(Rev%201).7z&eruda=true). It will work on every device I have tried except for iOS.

**Comment by Wamy-Dev** [comment]
This is what the network tab looks like on iOS ![image](https://user-images.githubusercontent.com/25761442/199887963-9a9980c5-149e-40cf-8519-58d7359815b5.png)

**Comment by Wamy-Dev** [comment]
Just realized that https://rawcdn.githack.com/ethanaobrien/emulatorjs/main/data/loader.js is not updated to the latest... can you fix this?

**Comment by ethanaobrien** [comment]
That's actually a cache thing, on both githacks side and on your phones side. Multiple refreshes (or/and waiting a few hours) should fix it. It should be updated on githacks side by now

**Comment by Wamy-Dev** [comment]
Alright, while the version may have changed, the problem still persists

**Comment by ethanaobrien** [comment]
@Wamy-Dev @Vimm2 can you try on the https://demo.emulatorjs.org/ website? I tested this on my iPhone just now (running iOS 16) and it worked just fine, so it appears to have fixed it, at least from my perspective. Could you test this please?

**Comment by Wamy-Dev** [comment]
it works on that demo site, but not on any other site

**Comment by ethanaobrien** [comment]
So it does look like the bug has been fixed (the demo site link I sent you is GitHub pages linked to that domain) here are some steps to debug why it may not be working

1. Make sure all data files are up to date
2. Clear all cache
3. Clear all cookies
4. Make sure your server is not caching anything
5. Try using GitHack to load the resources, see if that makes a difference.

Let me know if none of this works

**Comment by Wamy-Dev** [comment]
The problem is: is that it doesnt work on any other website though. 

[Example 1](https://crocdb.net/play?link=nointro.atari-2600/Mario%20Bros.%20%28USA%29.7z&title=Mario%20Bros&platform=atari2600&beta1=false)

[Example 2](https://rezi.one/play?type=arcade&link=https://archive.org/download/mame-merged/mame-merged//mario.zip&bios=null&title=mario.zip)

Cache is disabled on Rezi completely for /play which is where the emulator lives. Crocdb uses EmulatorJS too but it doesnt work either...

**Comment by ethanaobrien** [comment]
That is the same problem as #378  you need to change https://rawcdn.githack.com/ethanaobrien/emulatorjs/main/data/ to https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/

**Comment by Wamy-Dev** [comment]
> That is the same problem as #378 you need to change https://rawcdn.githack.com/ethanaobrien/emulatorjs/main/data/ to https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/

I have replaced it on rezi.one, and mobile still does not work...

**Comment by ethanaobrien** [comment]
Try using https://raw.githack.com/EmulatorJS/EmulatorJS/main/data/ instead. I looked at the code, this seems to be a problem with githack file caching

**Comment by Wamy-Dev** [comment]
wow that works! Thank you!
