### ISSUE TITLE
Cache/Download percentage - doesn't support 7z files (only zip) + shaders error message on psx core

### ISSUE THREAD

**Issue by shay-la** [emulatorjs/emulatorjs#347]
Hi,

First of all I don't understand why you blocked my previous account (shaylevary), after all I'm trying here to help this project and I didn't do anything wrong.
It is the essence of any project, to perform QA tests to report bugs in each new version/update - in order to get them solved.
No software is free from bugs, so if I had the knowledge in programming i would sure try to help, but since I have no programming knowledge, I'm trying to help this project as much as I can, because I really admire the wonderful work you do here.

**If you want me to stop reporting this bugs, then I will respect and stop reporting bugs and error codes location.**

In any case, After a test I performed I found that the reason why download progress does not appear for me is because file with extensions:  **.7z, PBP, CHD** isn't supported. Only when I use files in .ZIP format, the download progress percentage appears correctly.
Personally i prefer to use PBP psx roms, because it doesn't required decompress of rom files after download.

The same goes for the cache file - Cache works fine only when using zip files, while 7z files gets download after each refresh.

Console error message during download progress:
Uncaught TypeError: Cannot create property 'innerHTML' on string '/data/extractzip.js?v=1'
    at XMLHttpRequest.onDownloadProgress (emu-main.js?v=23.8:1899:69)
onDownloadProgress @ emu-main.js?v=23.8:1899
XMLHttpRequest.send (async)
(anonymous) @ emulator.js?v=23.8:221
_0x33171 @ emulator.js?v=23.8:199
get @ emulator.js?v=23.8:253
_0x574747 @ emu-main.js?v=23.8:1896
(anonymous) @ emu-main.js?v=23.8:1915
_0x2b6d6d.oncomplete @ emulator.js?v=23.8:404

The other thing I reported last week was about the shaders that stopped working in the PSX core games. Don't know if this helps, but when I try to run one of the shaders I get the following error message:

Uncaught TypeError: str.charCodeAt is not a function
    at lengthBytesUTF8 (eval at _0x54d695 (emu-main.js?v=23.8:1960:44), <anonymous>:1:16934)
    at Object.writeFile (eval at _0x54d695 (emu-main.js?v=23.8:1960:44), <anonymous>:1:137914)
    at Object.setShader (emu-main.js?v=23.8:3365:34)
    at HTMLDivElement.<anonymous> (emu-main.js?v=23.8:5308:35)
    at _0x6954aa._0xbae705 (emu-main.js?v=23.8:253:23)
    at start (emu-main.js?v=23.8:1484:43)
    at Worker._0x99321 (emu-main.js?v=23.8:1496:41)

**Apologies in advance if it bothers you that i reporting these bugs, i would stop post any more bugs if i would be requested.**

**Comment by ethanaobrien** [comment]
Reporting the bugs is fine. Based on the error code for the PlayStation shaders I can't fix it without upgrading the wasm and I have gotten a chance to sit down and fix that. With that other error code, that's reasonable, I can look into why that stuff is happening.

The main reason I blocked you was because on your website (minigames.co.li) there was no clear statement of if any changes were made to the emulator and there was no clear statement of where the emulator came from, which is against the license. I just ask you to add a message/page where people can know where it came from and if any changes were made

**Comment by shay-la** [comment]
First of all, I have never made any changes to your original script code, I am using the original code that appears on your site, I have not changed the credit that belongs to you in the code of the script or made any changes on the script files.
In addition, my site is not officially online yet, it is only made for testing purpose for now, and it got only 10 games that runs in different emulators, for experiment only.

Regarding a clear statement of where the emulator came from - I have no problem to add this line, I just didn't know that it was required in order to run this script, as the script code as already got your credits inside on the right click menu.

But if it's part of the requirement, just tell me where I should add this line and be sure i'll add it immediately.

Please don't be mad on me, I really didn't mean to harm, or take the credit you deserve for your great work, this is a mistake made in good faith and not on purpose.

**Comment by ethanaobrien** [comment]
Yeah it's one of the things required by the License, to point to the original project, I really don't care where on the site it is, it could be like a message below the emulator, on the main page, on the cookies policy page, it doesn't really matter. Thanks for being willing to put the message. I should be able to fix all these bugs tomorrow (except the PlayStation one)

**Comment by shay-la** [comment]
Ok, Thank you. I will add the credits on the cookies policy page, if it's ok with you, and also appreciate if you can please remove my account block. :)

**Comment by ethanaobrien** [comment]
I'll do that, thank you

**Comment by ethanaobrien** [comment]
This should be fixed. Can you confirm and then I will close?

**Comment by shaylevary** [comment]
The error message that appeared in console before during the rom download has disappeared, but problem still not solved, only when loading .zip rom files the download percentage appear.

**Comment by ethanaobrien** [comment]
This is really strange, this isnt happening for me. Could you set up a simple server with the most basic settings and see which one breaks it or if it doesnt work in the first place? Is this only for a specific system? With or without bios?

**Comment by shaylevary** [comment]
This problem accures in all systems when trying to load .7z file rom (when using .zip it's working good and show the download data percentage).

Here is the simple code i use:

<div id="game"></div>
<script type="text/javascript">
 EJS_player = '#game';
 EJS_startOnLoaded = false; 
EJS_core = 'psx';
 EJS_biosUrl = '/engine/console/bios/psx_old.zip';
 EJS_gameUrl = '/wp-content/uploads/games/console/C/ccrashb1.7z';
 EJS_pathtodata = '/engine/console/data/';
EJS_DEBUG_XX = true;
</script>
<script src="/engine/console/data/loader.js"></script>

**Comment by ethanaobrien** [comment]
Thats strange, I'll look at this when I can

**Comment by shaylevary** [comment]
Ok, thank you. 
You may try test it on my site, and if you want I can give you a link to this simple script running on my server.

**Comment by shay-la** [comment]
I would like to update that my system admin was able to find the necessary server settings in order to add support in displaying the download percentages for PBP and 7z files.
I would like to thank you for all the help and information you've provided on this issue that helped solve this problem.

You may close this ticket, if the issue of support for shaders for psx cores is already being handled separately.

Thanks in advance.

**Comment by ethanaobrien** [comment]
Awesome, thank you
