### ISSUE TITLE
Keyboard letters doesn't response when current language is set to something other than English

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#647]
Hi,

When I am using Windows operating system and uses language other than English, the letter buttons on the keyboard do not respond to presses (unless I change the language to English using Alt-Shift).

Is it possible to add support for all keyboard keys regardless of the currently active language.

**Comment by ethanaobrien** [comment]
@allancoding

**Comment by allancoding** [comment]
Is it just the letter keys?

**Comment by shaylevary** [comment]
Yes.

On the previous v3.xx you've used Keycode number for each key, so the typing language that was currently set didn't affect the buttons.
Starting of v4.xx, the KeyCode was replaced with English letters, which causes a problem in case the keyboard typing letters is set to something else than English.

**Comment by allancoding** [comment]
Ok I will add an exception for that.

**Comment by allancoding** [comment]
Fixed in #661

**Comment by shaylevary** [comment]
I've tried to add the new keycode values to my script, but it still doesn't seems to work when switching to other language than English.

I will appreciate any help.

Here is the input code that i've added:

EJS_defaultControls={0:{0:{value:"x",value2:"BUTTON_2",keycode:"88"},1:{value:"s",value2:"BUTTON_4",keycode:"83"},2:{value:"v",value2:"SELECT",keycode:"86"},3:{value:"enter",value2:"START",keycode:"13"},4:{value:"arrowup",value2:"DPAD_UP",keycode:"38"},5:{value:"arrowdown",value2:"DPAD_DOWN",keycode:"40"},6:{value:"arrowleft",value2:"DPAD_LEFT",keycode:"37"},7:{value:"arrowright",value2:"DPAD_RIGHT",keycode:"39"},8:{value:"z",value2:"BUTTON_1",keycode:"90"},9:{value:"a",value2:"BUTTON_3",keycode:"65"},10:{value:"q",value2:"LEFT_TOP_SHOULDER",keycode:"81"},11:{value:"e",value2:"RIGHT_TOP_SHOULDER",keycode:"69"},12:{value:"e",value2:"LEFT_BOTTOM_SHOULDER",keycode:"69"},13:{value:"w",value2:"RIGHT_BOTTOM_SHOULDER",keycode:"87"},14:{value2:"LEFT_STICK"},15:{value2:"RIGHT_STICK"},16:{value:"h",value2:"LEFT_STICK_X:+1",keycode:"72"},17:{value:"f",value2:"LEFT_STICK_X:-1",keycode:"70"},18:{value:"g",value2:"LEFT_STICK_Y:+1",keycode:"71"},19:{value:"t",value2:"LEFT_STICK_Y:-1",keycode:"84"},20:{value:"l",value2:"RIGHT_STICK_X:+1",keycode:"76"},21:{value:"j",value2:"RIGHT_STICK_X:-1",keycode:"74"},22:{value:"k",value2:"RIGHT_STICK_Y:+1",keycode:"75"},23:{value:"i",value2:"RIGHT_STICK_Y:-1",keycode:"73"},24:{},25:{},26:{},27:{},28:{},29:{}},1:{},2:{},3:{}};

Also, when i enter to the key configuration, i don't see any keycode table that i can change:
![key-config](https://github.com/EmulatorJS/EmulatorJS/assets/10597517/0ba49498-206b-47a2-907e-62f4be02e63b)

**Comment by allancoding** [comment]
The keyCode value is automatically set. What browser are you using because. It worked for me. What keyboard language are you using?
Maybe try clearing you cache?

**Comment by shaylevary** [comment]
I'm using chrome browser on pc.
The letters buttons doesn't response when I switch to Hebrew language on my keyboard.
I've tried also to clean the cache but it didn't help.

Btw why do I need to set keychar+keycode on the settings file?
Example: {value:"s",value2:"BUTTON_4",keycode:"83"}

Why can't I set the keychar only and the emulator script will automatically convert it to keycode?

**Comment by shaylevary** [comment]
BTW, I've tested this issue on the demo site (demo.emulatorjs.org), and it doesn't seems also to work when switching to Hebrew (UTF-8) language on keyboard.
On previous v3.xx it used only keycode, and it seems to work fine no matter which language was currently set on the keyboard.

**Comment by allancoding** [comment]
I will change this to use the keycode method.

**Comment by allancoding** [comment]
@shaylevary make sure to reset your controller values with the button to see the changes.

**Comment by shaylevary** [comment]
Now works great, thank you.

You Should fix this values code on emulator.js file in order to make the arrow keys to work correctly:


            5: {
                'value': 'arrowdown', **=> 'down arrow'**
                'value2': 'DPAD_DOWN',
                'keycode': 40
            },
            6: {
                'value': 'arrowleft',  **=> 'left arrow'**
                'value2': 'DPAD_LEFT',
                'keycode': 37
            },
            7: {
                'value': 'arrowright', **=>'right arrow'**
                'value2': 'DPAD_RIGHT', 
                'keycode': 39
            },

**Comment by allancoding** [comment]
I will do that and remove the keyCode value from the default config. And update the docs.
